# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import post_office.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0006_attachment_mimetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=post_office.models.get_upload_path, verbose_name='File')),
                ('name', models.CharField(help_text='The original filename', max_length=255, verbose_name='Name')),
                ('mimetype', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template_emails', models.ManyToManyField(related_name='attachment_templates', to='post_office.EmailTemplate')),
            ],
            options={
                'verbose_name': 'Attachment Template',
                'verbose_name_plural': 'Attachments Template',
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mimetype',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
