# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0007_auto_20170713_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, help_text="The fields between '{{' and '}}' are the variables while the text that is included in the tags '{% comment%}' and '{% endcomment%}' will not be rendered in the mail \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 <br/> Do not remove the fields included in the tags '{%' '%}'", validators=[post_office.validators.validate_template_syntax], verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, help_text="The fields between '{{' and '}}' are the variables while the text that is included in the tags '{% comment%}' and '{% endcomment%}' will not be rendered in the mail \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 <br/> Do not remove the fields included in the tags '{%' '%}'", validators=[post_office.validators.validate_template_syntax], verbose_name='HTML content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text="e.g: 'welcome_email' -- Do not change this field! It is for internal use only", max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
    ]
